apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productcatalogservice
spec:
  host: productcatalogservice
  subsets:
  - name: vm
    labels:
      version: vm
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productcatalogservice-local
spec:
  host: productcatalogservice-local
  subsets:
  - name: local
    labels:
      version: local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productcatalogservice
spec:
  hosts:
    - productcatalogservice
  http:
  - route:
    - destination:
        host: productcatalogservice #VM
      weight: 90
    - destination:
        host: productcatalogservice-local
        subset: local
      weight: 10